SYNCQT.HEADER_FILES = ../../include/QtInference/qtinference.h
SYNCQT.HEADER_CLASSES = ../../include/QtInference/QtInference
SYNCQT.PRIVATE_HEADER_FILES =
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.INJECTIONS = 
